# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
alias vi="/usr/bin/nvim"
alias vim="/usr/bin/nvim"
alias nano="/usr/bin/nvim"

export EDITOR="/usr/bin/nvim"
export VISUAL="/usr/bin/nvim"

